name: Build Docker Image
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    uses: a-safe-digital/actions/.github/workflows/build-docker-image.yaml@v7.1
    secrets:
      NPM_TOKEN: ${{ secrets.GH_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.CONEK_DEV_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.CONEK_DEV_AWS_SECRET_ACCESS_KEY }}
    with:
      DOCKERFILE_PATH: Dockerfile
      IMAGE_NAME: echo-server
      AWS_REGION: us-east-2
